[package]
name = "nostrlight"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
confy = "1.0.0"
gtk4 = "0.9.6"
nostr = "0.41.0"
serde = { version = "1.0.219", features = ["derive"] }
